### PR TITLE
Fix stream reader

### PR DESCRIPTION
**Pull request by patmmm**

### CODE REVIEW

**Comment by rohitsangwan01** [comment]
@patmmm Thank you for the PR, can you please tell which issue this Pr fixes, like you can mention any issue raised by someone, or your useCase, like
previously Expecting [THIS] and was getting [THIS]
and this PR fixed that issue now

**Comment by patmmm** [comment]
I think the similar issue is #6. Sometimes, data from the stdout stream contains more than one message, e.g., event = "[datalength][jsondata][datalength][jsondata]", and this causes some data loss because it returns null from the function.

**Comment by rohitsangwan01** [comment]
> I think the similar issue is #6. Sometimes, data from the stdout stream contains more than one message, e.g., event = "[datalength][jsondata][datalength][jsondata]", and this causes some data loss because it returns null from the dataParser function.

i see, i was not able to replicate this with my ble device, are you able to replicate that issue, and if yes, is that issue fixed now with this pr ?
seems like https://github.com/rohitsangwan01/win_ble/issues/9 is also similar

**Comment by patmmm** [comment]
This PR solves my issue.
Actually, you can replicate the data loss issue since the project startup.

Here is an example of missing 2 messages during startup.
image

**Comment by rohitsangwan01** [comment]
@patmmm ok thank you, will try this

**Pull request merged**
